version: '3.8'

services:
  nyc-taxi-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nyc-taxi-cloud
    restart: unless-stopped
    
    volumes:
      - /home/riorustiadi/docker/volumes/nyc-taxi-cloud/data:/app/data
      - /home/riorustiadi/docker/volumes/nyc-taxi-cloud/logs:/app/logs
    
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - TZ=UTC
    
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2G
    #       cpus: '1.0'
    #     reservations:
    #       memory: 512M
    #       cpus: '0.5'
    
    networks:
      - nyc-taxi-network
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import pandas, pyarrow, requests, holidays; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  nyc-taxi-network:
    driver: bridge